### ISSUE TITLE
Huge Panels in New Releases

### ISSUE THREAD

**Issue by ThePhaseless** [spicetify/spicetify-cli#1605]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v2.9.6
- Spicetify version: Spotify for Windows
1.1.83.956.gbe7ea9a7
```

### 📝 Description

Just clean installed spotify with spicetify to confirm this, and just with new releases addon installed it looks like this

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/33990351/164892234-94199008-91a8-43a5-9fcd-30d544877cc2.png)

**Comment by ThePhaseless** [comment]
Before reinstalling it was also happening in marketplace

**Comment by MOL0V** [comment]
Same issue, tryied allot of ways to fix, but nothing help

**Comment by Exhigh** [comment]
It's got to do with the (.main-gridContainer-gridContainer) css class being switched from having its values hard-coded to being changed such that it has its values being determined by variables.
Plus the method that was used to arrange the grid has been changed (css wise).

**Comment by theRealPadster** [comment]
Some more context:
![Screenshot_20220423-210902](https://user-images.githubusercontent.com/1565883/164951408-d331e5f6-64c9-4b3d-b994-b1f515015913.png)

(I would paste but I'm on my phone right now)

**Comment by ririxidev** [comment]
Resolved by https://github.com/spicetify/spicetify-cli/commit/7e81937e7c1584ab56b62831ba13b5afdf89d525

**Comment by ThePhaseless** [comment]
The issue is still present in marketplace

**Comment by ririxidev** [comment]
Please open an issue in spicetify-marketplace then.

**Comment by guttitto** [comment]
For me, the problem persists both on New Releases and Reddit.

**Comment by guttitto** [comment]
- Spotify version: 1.1.83.956.gbe7ea9a7 / Windows
- Spicetify version: 2.9.7
![image](https://user-images.githubusercontent.com/25709670/165210788-400901c8-05ec-40e6-bd79-14d458e8a3b7.png)
![image](https://user-images.githubusercontent.com/25709670/165210922-609d8eb3-0bec-4021-a3da-6075397ff144.png)

**Comment by afonsojramos** [comment]
Does `spicetify restore backup apply` fix the issue @guttitto?

**Comment by guttitto** [comment]
I had to replace the New Releases folder manually, now it's fixed, but Reddit is still bugged.
